default: &default
  adapter: postgresql
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  local_infile: true
  username: "root"
  password: "root"
  socket: "/var/run/mysqld/mysqld.sock"

development:
  <<: *default
  database: sendgird_db
